// vin: utxo finder
export const USER_OPEN_UTXO_FINDER_MODAL = 'STD_USER_OPEN_UTXO_FINDER_MODAL';
export const USER_CLOSE_UTXO_FINDER_MODAL = 'STD_USER_CLOSE_UTXO_FINDER_MODAL';
export const USER_SEARCH_UTXOS = 'STD_USER_SEARCH_UTXOS';
export const REDUCER_RECEIVE_UTXOS = 'STD_REDUCER_RECEIVE_UTXOS';
export const USER_SET_UTXO = 'STD_USER_SET_UTXO';
export const REDUCER_RECEIVE_UTXO = 'STD_REDUCER_RECEIVE_UTXO';

// vin: signature creator
export const USER_OPEN_SIGNATURE_CREATOR_MODAL = 'STD_USER_OPEN_SIGNATURE_CREATOR_MODAL';
export const USER_CLOSE_SIGNATURE_CREATOR_MODAL = 'STD_USER_CLOSE_SIGNATURE_CREATOR_MODAL';
export const USER_DUMP_PRVKEY = 'STD_USER_DUMP_PRVKEY';
export const REDUCER_RECEIVE_PRVKEY = 'STD_REDUCER_RECEIVE_PRVKEY';
export const USER_CERATE_SIGNATURE = 'STD_USER_CERATE_SIGNATURE';
export const REDUCER_RECEIVE_SIGNATURE = 'STD_REDUCER_RECEIVE_SIGNATURE';

// vout: script template finder
export const USER_OPEN_TEMPLATE_FINDER_MODAL = 'STD_USER_OPEN_TEMPLATE_FINDER_MODAL';
export const USER_CLOSE_TEMPLATE_FINDER_MODAL = 'STD_USER_CLOSE_TEMPLATE_FINDER_MODAL';
export const USER_SET_SCRIPT_TEMPLATE = 'STD_USER_SET_SCRIPT_TEMPLATE';
export const REDUCER_RECEIVE_SCRIPT_TEMPLATE = 'STD_REDUCER_RECEIVE_SCRIPT_TEMPLATE';

// vin amount
export const REDUCER_RECEIVE_VIN_AMOUNT = 'STD_REDUCER_RECEIVE_VIN_AMOUNT';

// vout value
export const USER_UPDATE_VOUT_VALUE = 'STD_USER_UPDATE_VOUT_VALUE';
export const REDUCER_RECEIVE_VOUT_VALUE = 'STD_REDUCER_RECEIVE_VOUT_VALUE';

// vout: script op code suggestion
export const USER_UPDATE_SCRIPT_WITH_SUGGEST = 'STD_USER_UPDATE_SCRIPT_WITH_SUGGEST';
export const REDUCER_RECEIVE_UPDATED_SCRIPT = 'STD_REDUCER_RECEIVE_UPDATED_SCRIPT';

// tx: fee
export const USER_UPDATE_AMOUNTS = 'STD_USER_UPDATE_AMOUNTS';
export const REDUCER_RECEIVE_AMOUNTS = 'STD_REDUCER_RECEIVE_AMOUNTS';

// tx: hex
export const USER_CONVERT_TO_TXHEX = 'STD_USER_CONVERT_TO_TXHEX';
export const REDUCER_RECEIVE_TXHEX = 'STD_REDUCER_RECEIVE_TXHEX';

// tx: send
export const USER_SEND_TX = 'STD_USER_SEND_TX';
export const REDUCER_RECEIVE_SEND_TX_RESULT = 'STD_REDUCER_RECEIVE_SEND_TX_RESULT';

// rpc:error
export const SYS_THROW_RPC_ERROR = 'STD_SYS_THROW_RPC_ERROR';
