export { AddBox } from '@material-ui/icons';
export { AddBox as AddBoxIcon } from '@material-ui/icons';
export { Add as AddIcon } from '@material-ui/icons';
export { ChevronRight as RightIcon } from '@material-ui/icons';
export { ChevronLeft as LeftIcon } from '@material-ui/icons';
export { Create } from '@material-ui/icons';
export { Description as CopyIcon } from '@material-ui/icons';
export { Edit as EditIcon } from '@material-ui/icons';
export { ExposureNeg1 as MinusIcon } from '@material-ui/icons';
export { ExposurePlus1 as PlusIcon } from '@material-ui/icons';
export { FiberNew as NewIcon } from '@material-ui/icons';
export { FlashOn as FlashOnIcon } from '@material-ui/icons';
export { Info as InfoIcon } from '@material-ui/icons';
export { IndeterminateCheckBox as RemoveBox } from '@material-ui/icons';
export { ListAlt as Template } from '@material-ui/icons';
export { PlayArrow as PlayIcon } from '@material-ui/icons';
export { Search } from '@material-ui/icons';
export { Search as SearchIcon } from '@material-ui/icons';
export { Settings as SettingsIcon } from '@material-ui/icons';
export { VpnKey as VpnKeyIcon } from '@material-ui/icons';
export { Error as ErrorIcon } from '@material-ui/icons';
