export const USER_GEN_HD_SEED = 'USER_GEN_HD_SEED';
export const REDUCER_RECEIVE_HD_SEED = 'REDUCER_RECEIVE_HD_SEED';

export const USER_GET_HD_MASTER_KEYS_FROM_SEED = 'USER_GET_HD_MASTER_KEYS_FROM_SEED';
export const USER_GET_HD_MASTER_KEYS_FROM_MNEMONIC = 'USER_GET_HD_MASTER_KEYS_FROM_MNEMONIC';
export const USER_GET_HD_MASTER_PUBKEY = 'USER_GET_HD_MASTER_PUBKEY';
export const REDUCER_RECEIVE_HD_MNEMONIC = 'REDUCER_RECEIVE_HD_MNEMONIC';
export const REDUCER_RECEIVE_HD_MASTER_KEYS = 'REDUCER_RECEIVE_HD_MASTER_KEYS';

export const USER_SET_HD_PATH = 'USER_SET_HD_PATH';
export const REDUCER_RECEIVE_HD_PATH = 'REDUCER_RECEIVE_HD_PATH';

export const USER_GET_HD_KEYS = 'USER_GET_HD_KEYS';
export const USER_GET_HD_PUBKEY = 'USER_GET_HD_PUBKEY';
export const REDUCER_RECEIVE_HD_KEYS = 'REDUCER_RECEIVE_HD_KEYS';

export const USER_CREATE_P2PKH_ADDR = 'USER_CREATE_P2PKH_ADDR';
export const REDUCER_RECEIVE_P2PKH_ADDR = 'REDUCER_RECEIVE_P2PKH_ADDR';

export const USER_CREATE_P2WPKH_ADDR = 'USER_CREATE_P2WPKH_ADDR';
export const REDUCER_RECEIVE_P2WPKH_ADDR = 'REDUCER_RECEIVE_P2WPKH_ADDR';
