export const USER_GET_BLOCK_COUNT = 'USER_GET_BLOCK_COUNT';
export const REDUCER_RECEIVE_BLOCK_COUNT = 'REDUCER_RECEIVE_BLOCK_COUNT';

export const USER_GENERATE_BLOCKS = 'USER_GENERATE_BLOCKS';
export const REDUCER_RECEIVE_BLOCK_IDS = 'REDUCER_RECEIVE_BLOCK_IDS';
