export const USER_UPDATE_CONFIG = 'USER_UPDATE_CONFIG';
export const REDUCER_RECEIVE_CONFIG = 'REDUCER_RECEIVE_CONFIG';

export const USER_CHANGE_BTC_NODE = 'USER_CHANGE_BTC_NODE';
export const REDUCER_RECEIVE_BTC_NODE = 'REDUCER_RECEIVE_BTC_NODE';
